### ISSUE TITLE
Does not patch rest api

### ISSUE THREAD

**Issue by Vindfrisk** [markshust/magento2-module-disabletwofactorauth#1] opened 2020-08-18 19:52 UTC
Not sure if you intended to also patch this? Anyhow you cant create REST tokens because of 2fa limitation. See response below.

```
{
    "message": "Please ask an administrator with sufficient access to configure 2FA first",
    "trace": "#0 [internal function]: Magento\\TwoFactorAuth\\Model\\AdminAccessTokenService->createAdminAccessToken()\n#1 /var/www/magento2/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()\n#2 /var/www/magento2/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process()\n#3 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch()\n#4 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent()\n#5 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#6 /var/www/magento2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins()\n#7 /var/www/magento2/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch()\n#8 /var/www/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#9 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(263): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#10 /var/www/magento2/pub/index.php(40): Magento\\Framework\\App\\Bootstrap->run()\n#11 {main}"
}
```

**Comment by markshust** [comment] 2020-08-26 14:24
Thanks for the issue report @Vindfrisk. Yes, I'll keep this issue open and will take any PR's that make this work. I would think this module should disable any functionality of 2FA no matter where it is.

**Comment by zeeshan2523806** [comment] 2020-11-09 06:52
@markshust @Vindfrisk do you guyz have any luck with it ? If not then i can create the patch and submit PR for it ?

**Comment by markshust** [comment] 2020-11-10 14:35
Just left a comment on the commit that just came in a few hours ago. Once I can test this and verify code is working, I can bring this in.

**Comment by simonmaass** [comment] 2021-01-11 17:03
We are having the same issue. Any update on this?

**Comment by markshust** [comment] 2021-01-11 18:09
Hi @simonmaass -- this is my first day back from a little break. I'll be spending the next couple weeks on open source stuff, so will be testing this out and merging it in shortly (hopefully within the next few hours).

**Comment by markshust** [comment] 2021-01-11 21:35
Issue confirmed on 2.4.1. Testing out PR/commit.

**Comment by markshust** [comment] 2021-01-12 14:20
Merged this PR, and also made some styling/coding updates on the other files to keep things consistent with the coding recommendations I made. Tagged as version 1.1.0.

**Comment by simonmaass** [comment] 2021-01-12 14:47
@markshust thank you for the fast implementation!

**Comment by simonmaass** [comment] 2021-01-14 11:47
@markshust If I try to enable it for the API i get the following error:

![image](https://user-images.githubusercontent.com/32599710/104587024-97e5ba00-5666-11eb-8ded-a20e4d550610.png)

**Comment by royduin** [comment] 2022-07-12 08:39
Got the same error, but just putting `twofactorauth/general/enable_for_api_token_generation` with value `0` into `core_config_data` seems to work.

**Comment by markshust** [comment] 2022-07-19 16:23
Thanks for this report & info @royduin -- I'll re-open this ticket so we can fix this.

**Comment by markshust** [comment] 2024-01-19 00:25
Whoah - this ticket has been sitting here for a while 😅

I really don't want to disable 2FA for API token generation by default, as I think it should be retained enabled for security purposes.

But it appears this error is occurring only when "Enable 2FA" is set to No, and "Enable 2FA for API Token Generation" is set to Yes. Is this correct?

If so, what do you think would be the best way to handle this situation?

**Comment by CalamityJames** [comment] 2024-07-03 14:37
> But it appears this error is occurring only when "Enable 2FA" is set to No, and "Enable 2FA for API Token Generation" is set to Yes. Is this correct?

This is indeed what happens, for anyone who wants to work around it for the time being, you can do it via the CLI:
```
bin/magento config:set twofactorauth/general/enable_for_api_token_generation 0
```

**Comment by markshust** [comment] 2024-11-05 16:47
I found out that API token generation is dependent on the main 2FA functionality. If the main 2FA is disabled, trying to use 2FA for API token generation wouldn't work properly since the underlying functionality is turned off.

It makes logical sense that API token 2FA should only work if the main 2FA is enabled, so I'll be merging in a fix to resolve this issue.

**Comment by markshust** [comment] 2024-11-05 16:52
This should be resolved in the PR that I just merged. I'll tag and release a new version momentarily. Thanks for your help with this, and sorry this fell by the wayside for so long!

**Closed as completed by markshust** 2024-11-05 16:52 UTC
