### ISSUE TITLE
unexpected 'ScopeConfigInterface'

### ISSUE THREAD

**Issue by orthener** [markshust/magento2-module-disabletwofactorauth#7] opened 2021-01-13 08:59 UTC
`se:di:compile` returns error
```
PHP Parse error:  syntax error, unexpected 'ScopeConfigInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /vendor/markshust/magento2-module-disabletwofactorauth/Plugin/BypassTwoFactorAuth.php on line 18
```
Need remove "ScopeConfigInterface" from string `private ScopeConfigInterface $scopeConfig;`

**Comment by cmacdonald-au** [comment] 2021-01-13 10:13
Dupe of #6

**Comment by markshust** [comment] 2021-01-13 14:51
Thanks, closing this as a dupe

**Closed as completed by markshust** 2021-01-13 14:51 UTC
